Added support for list of status descriptions.
EBI-Metagenomics/ebi-metagenomics-libs pull request #6
Opened 2019-05-08 15:09 UTC by mscheremetjew

2019-05-08 15:41 UTC, mb1069 requested changes

2019-05-08 15:41 UTC, mb1069 commented on mgnify_backlog/mgnify_handler.py
> +    def get_annotation_jobs(self, run_or_assembly_accessions=None, study_accessions=None, status_descriptions=list(),
```suggestion
    def get_annotation_jobs(self, run_or_assembly_accessions=None, study_accessions=None, status_descriptions=None,
```
Don't use mutable default arguments; these are instantiated when the function is defined and can therefore cause side effects when the function is later called. https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

2019-05-08 15:41 UTC, mb1069 commented on mgnify_backlog/mgnify_handler.py
> +                status_descriptions = list([status_descriptions])
```suggestion
                status_descriptions = [status_descriptions]
```
Already making a list, no need for type casting

2019-05-09 10:09 UTC, mscheremetjew reviewed
All makes sense. Thanks for the review.

2019-05-09 11:23 UTC, merged